main = ".open-next/worker.js"
name = "blueshift-dashboard"
compatibility_date = "2025-09-01"
compatibility_flags = ["nodejs_compat"]
find_additional_modules = true
base_dir = "src/app"
rules = [
  { type = "Text", globs = ["**/*.mdx"], fallthrough = true }
]


[observability]
enabled = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
